--USE master

USE IPEKSUARITMADATABASE
GO

ALTER TABLE PHONENUMBER ADD FOREIGN KEY(CustomerID) REFERENCES CUSTOMER(CustomerID)
GO

ALTER TABLE CUSTOMER ADD FOREIGN KEY(TRIdentifyNo) REFERENCES PERSON(TRIdentifyNo)
GO

ALTER TABLE EMPLOYEE ADD FOREIGN KEY(TRIdentifyNo) REFERENCES PERSON(TRIdentifyNo)
GO

ALTER TABLE SALES ADD FOREIGN KEY(SaleCustomerID) REFERENCES CUSTOMER(CustomerID)
GO

ALTER TABLE SALES ADD FOREIGN KEY(SaleEmployeeID) REFERENCES EMPLOYEE(EmployeeID)
GO

ALTER TABLE PRODUCTS ADD FOREIGN KEY(ProductSourceFirmID) REFERENCES SOURCEFIRM(FirmID)
GO

ALTER TABLE STOCK ADD FOREIGN KEY(StockProductID) REFERENCES PRODUCTS(ProductID)
GO

ALTER TABLE SALESPRODUCT ADD FOREIGN KEY(ProductID) REFERENCES PRODUCTS(ProductID)
GO

ALTER TABLE SALESPRODUCT ADD FOREIGN KEY(SaleContractNumber) REFERENCES SALES(ContractNumber)
GO

ALTER TABLE LICENSE ADD FOREIGN KEY(LicenseProductID) REFERENCES PRODUCTS(ProductID)
GO

ALTER TABLE SERVICE ADD FOREIGN KEY(ServiceCustomerID) REFERENCES CUSTOMER(CustomerID)
GO

ALTER TABLE SERVICE ADD FOREIGN KEY(ServiceEmployeeID) REFERENCES EMPLOYEE(EmployeeID)
GO

ALTER TABLE SERVICEPRODUCT ADD FOREIGN KEY(ServiceID) REFERENCES SERVICE(ServiceID)
GO

ALTER TABLE SERVICEPRODUCT ADD FOREIGN KEY(ProductID) REFERENCES PRODUCTS(ProductID)
GO

ALTER TABLE SERVICEREQUEST ADD FOREIGN KEY(ServiceRequestCustomerID) REFERENCES CUSTOMER(CustomerID)
GO

ALTER TABLE SERVICEINSTALLMENT ADD FOREIGN KEY(InstallmentServiceID) REFERENCES SERVICE(ServiceID)
GO

ALTER TABLE SERVICEINSTALLMENT ADD FOREIGN KEY(InstallmentCustomerID) REFERENCES CUSTOMER(CustomerID)
GO

ALTER TABLE SALESINSTALLMENT ADD FOREIGN KEY(InstallmentContractNumber) REFERENCES SALES(ContractNumber)
GO

ALTER TABLE SALESINSTALLMENT ADD FOREIGN KEY(InstallmentCustomerID) REFERENCES CUSTOMER(CustomerID)
GO